"""Add biometric authentication support

Revision ID: 2e280e9a14d7
Revises: 4c43a6b36ab1
Create Date: 2026-01-05 02:22:40.952370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e280e9a14d7'
down_revision = '4c43a6b36ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biometric_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('biometric_credentials', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pending_webauthn_challenge', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pending_challenge_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('biometric_enrolled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('require_biometric_for_voting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biometric_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('biometric_credential_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('biometric_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_column('verification_method')
        batch_op.drop_column('biometric_verified_at')
        batch_op.drop_column('biometric_credential_id')
        batch_op.drop_column('biometric_verified')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('require_biometric_for_voting')
        batch_op.drop_column('biometric_enrolled_at')
        batch_op.drop_column('pending_challenge_expires')
        batch_op.drop_column('pending_webauthn_challenge')
        batch_op.drop_column('biometric_credentials')
        batch_op.drop_column('biometric_enabled')

    # ### end Alembic commands ###
