"""Add email verification and phone uniqueness constraints

Revision ID: 4c43a6b36ab1
Revises: 
Create Date: 2026-01-01 22:07:02.254175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c43a6b36ab1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_audit_logs_user'))

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('social_media',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('candidates_position_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'positions', ['position_id'], ['id'])

    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_elections_active'))

    with op.batch_alter_table('flagged_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_flagged_activities_election'))
        batch_op.drop_column('metadata')

    with op.batch_alter_table('ml_model_configuration', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('threshold_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('feature_weights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('accuracy_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('election_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('positions_election_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'elections', ['election_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expires', sa.DateTime(), nullable=True))
        batch_op.alter_column('custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_voter_id'))
        batch_op.create_unique_constraint(None, ['email_verification_token'])
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('election_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('geo_location',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('detection_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_votes_candidate'))
        batch_op.drop_index(batch_op.f('idx_votes_election'))
        batch_op.drop_index(batch_op.f('idx_votes_flagged'))
        batch_op.drop_index(batch_op.f('idx_votes_user'))
        batch_op.drop_constraint(batch_op.f('votes_election_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('votes_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('votes_candidate_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('votes_position_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'positions', ['position_id'], ['id'])
        batch_op.create_foreign_key(None, 'candidates', ['candidate_id'], ['id'])
        batch_op.create_foreign_key(None, 'elections', ['election_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('votes_position_id_fkey'), 'positions', ['position_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('votes_candidate_id_fkey'), 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('votes_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('votes_election_id_fkey'), 'elections', ['election_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_votes_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_votes_flagged'), ['is_flagged'], unique=False)
        batch_op.create_index(batch_op.f('idx_votes_election'), ['election_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_votes_candidate'), ['candidate_id'], unique=False)
        batch_op.alter_column('detection_features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('geo_location',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('election_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_users_voter_id'), ['voter_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.alter_column('custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('email_verification_token_expires')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('positions_election_id_fkey'), 'elections', ['election_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('election_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ml_model_configuration', schema=None) as batch_op:
        batch_op.alter_column('accuracy_metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('feature_weights',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('threshold_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('parameters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('flagged_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_flagged_activities_election'), ['election_id'], unique=False)
        batch_op.alter_column('reasons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('extra_metadata')

    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_elections_active'), ['is_active'], unique=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('candidates_position_id_fkey'), 'positions', ['position_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('social_media',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('position_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_logs_user'), ['user_id'], unique=False)
        batch_op.alter_column('details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
