"""Add require_biometric column to elections

Revision ID: e53edabbb844
Revises: 2e280e9a14d7
Create Date: 2026-01-06 16:21:44.242802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53edabbb844'
down_revision = '2e280e9a14d7'
branch_labels = None
depends_on = None


def upgrade():
    # Add column as nullable first
    op.add_column('elections', sa.Column('require_biometric', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute('UPDATE elections SET require_biometric = FALSE WHERE require_biometric IS NULL')
    
    # Now make it NOT NULL
    op.alter_column('elections', 'require_biometric', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_column('require_biometric')

    # ### end Alembic commands ###
